# Generated by Django 3.2.7 on 2021-10-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('num_pages', models.PositiveIntegerField()),
                ('published_date', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
